### ISSUE TITLE
Python traceback when trying to run electrum-dash

### ISSUE THREAD

**Issue by PostPollux** [dashpay/electrum-dash-old#88]
Like stated in the readme I just downloaded the "tar.gz" file, extracted it and tried to run it with console using the "./electrum-dash"  command. Unfortunately I get the following traceback:

Traceback (most recent call last):
  File "./electrum-dash", line 68, in <module>
    imp.load_module('electrum_dash', *imp.find_module('lib'))
  File "/home/johannesw/Downloads/electrum-dash-2.4.1/lib/__init__.py", line 3, in <module>
    from wallet import WalletSynchronizer, WalletStorage
  File "/home/johannesw/Downloads/electrum-dash-2.4.1/lib/wallet.py", line 34, in <module>
    from bitcoin import *
  File "/home/johannesw/Downloads/electrum-dash-2.4.1/lib/bitcoin.py", line 31, in <module>
    import x11_hash
ImportError: No module named x11_hash

Any idea? The readme says:  "all the python dependencies are included in the 'packages' directory". I can't find this directory. Where is it supposed to be?

Btw, I'm running Linux Manjaro

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
